name = "Pug"
grammar = "pug"
path_suffixes = ["pug"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
autoclose_before = ")}]"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
]
